version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: diff calendar.json
          command: |
            curl https://thaiprogrammer-tech-events-calendar.spacet.me/calendar.json > /tmp/master-calendar.json && diff -u /tmp/master-calendar.json public/calendar.json || true
      - run:
          name: diff calendar.ics
          command: |
            curl https://thaiprogrammer-tech-events-calendar.spacet.me/calendar.ics > /tmp/master-calendar.ics && diff -u /tmp/master-calendar.ics public/calendar.ics || true
      - store_artifacts:
          path: ~/src/public
          prefix: public
