version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - run:
          name: generate CI comment
          when: always
          command: |
            mkdir -p tmp && node scripts/generate-ci-comment.js | tee tmp/ci-comment.txt && node scripts/post-ci-comment.js
      - store_artifacts:
          path: ~/src/public
          prefix: public
